#!/bin/bash
#SBATCH --job-name=IQ-TREE_MF
#SBATCH --output=IQ-TREE_MF.out
#SBATCH --error=IQ-TREE_MF.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=128G
#SBATCH --time=2-00:00:00

# Now we can run IQ-TREE to build a phylogeny based on the concatenated alignment file
# As a first step, we need to run a model finder to search for the best model to use for the dataset

# STEP 1:
# Define the input and output folders
# The input will use the concatenated alignment and partition files generated by AMAS

Input=/data/AMAS
Output=/data/IQ-Tree/ModelSearch
mkdir -p $Output

# STEP 2:
# Load and run IQ-TREE model search with flag -m MFP

ml IQ-TREE/1.6.12-foss-2018b

iqtree -s $Input/concatenated.fasta -spp $Input/partitions.txt -m MFP -nt 32 -st DNA -pre $Output/MF









